import gallery from "@/lib/gallery-data.json";

export type AreaCasePhoto = { label: string; src: string; alt: string; width: number; height: number; position?: string };
export type AreaCase = {
  href: string;
  province: string;
  region: string;
  service: string;
  eyebrow: string;
  title: string;
  body: string;
  cta: string;
  photos: AreaCasePhoto[];
};

// 광역 → 시·군 → 서비스 순서는 아래 목록에 처음 나온 순서를 따른다.
// 새 사례는 areaCases에 한 줄 추가하면 선택지와 건수가 자동으로 반영된다.

const waxPhoto = gallery.find(category => category.slug === "floor-wax")!.items.find(item => item.id === "floor-wax-g28")!;
const pair = (labels: readonly [string, string], srcs: readonly [string, string], alt: string): AreaCasePhoto[] =>
  labels.map((label, i) => ({ label, src: srcs[i], alt: `${alt} · ${label}`, width: 900, height: 1200 }));
const beforeAfter = ["작업 전", "작업 후"] as const;
const caseEyebrow = "실제 작업 사례 · 비용과 견적 기준";

export const areaCases: AreaCase[] = [
  {
    href: "/바닥-왁스-코팅/경기도-안양시/", province: "경기도", region: "안양시", service: "바닥왁스코팅",
    eyebrow: "실제 작업 사진 · 비용과 견적 기준", title: "안양 바닥왁스코팅",
    body: "학원·음식점·업무시설·사무실의 작업 전후 사진을 확인하세요. 한식뷔페 현장에서 두꺼운 왁스를 박리하고 집기를 나눠 옮기며 작업한 과정도 담았습니다.",
    cta: "안양 사례와 견적 기준 보기",
    photos: [
      { label: "작업 전", src: `/images/gallery-v2/${waxPhoto.before}`, alt: `${waxPhoto.title} · 작업 전`, width: waxPhoto.beforeWidth, height: waxPhoto.beforeHeight },
      { label: "작업 후", src: `/images/gallery-v2/${waxPhoto.after}`, alt: `${waxPhoto.title} · 작업 후`, width: waxPhoto.afterWidth, height: waxPhoto.afterHeight },
    ],
  },
  {
    href: "/주방청소/경기도-안양시/", province: "경기도", region: "안양시", service: "주방청소",
    eyebrow: "실제 작업 사진 · 작업 범위와 견적 기준", title: "안양 주방청소",
    body: "배달 돈까스 주방의 튀김기·후드·기기 아래 사진을 살펴보세요. 내부 세척과 기기 이동 등 별도 확인 항목, 견적 조건과 상담 준비사항을 안내합니다.",
    cta: "안양 주방 사진과 견적 기준 보기",
    photos: [
      { label: "튀김기", src: "/images/anyang-kitchen/003.jpg", alt: "튀김기 테두리와 안쪽 벽면에 갈색·검은색 오염이 보이는 모습", width: 4000, height: 2252 },
      { label: "후드 안쪽", src: "/images/anyang-kitchen/004.jpg", alt: "후드 안쪽 판과 원형 배기구 주변에 점상 오염과 흘러내린 자국이 보이는 모습", width: 1440, height: 1081, position: "25% 50%" },
    ],
  },
  {
    href: "/바닥-왁스-코팅/경기도-성남시-분당구/", province: "경기도", region: "분당구", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "분당 바닥왁스코팅",
    body: "왁스가 고르게 자리 잡기 까다로운 회색 데코타일 사무실을 6명이 9시간 동안 세척하고 코팅한 기록입니다.",
    cta: "분당 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional-wax/bundang/01-floor-before.webp", "/images/regional-wax/bundang/06-wax-after.webp"], "분당 데코타일 사무실 바닥왁스코팅"),
  },
  {
    href: "/바닥-왁스-코팅/경기도-성남시/", province: "경기도", region: "성남시", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "성남 바닥왁스코팅",
    body: "의자 바퀴자국과 사용 오염이 심했던 100평 지식산업센터 디럭스타일을 3명이 8시간 동안 퇴거청소하고 코팅한 기록입니다.",
    cta: "성남 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional-wax/seongnam/01-wheel-marks-before.webp", "/images/regional-wax/seongnam/06-wax-after.webp"], "성남 지식산업센터 바닥왁스코팅"),
  },
  {
    href: "/바닥-왁스-코팅/경기도-성남시-판교/", province: "경기도", region: "판교", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "판교 바닥왁스코팅",
    body: "돌타일처럼 보이는 데코타일의 상당한 바닥오염을 약품으로 제거하고 3명이 6시간 동안 은은하게 코팅한 기록입니다.",
    cta: "판교 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional-wax/pangyo/02-contamination-before.webp", "/images/regional-wax/pangyo/06-wax-after.webp"], "판교 데코타일 바닥왁스코팅"),
  },
  {
    href: "/바닥-왁스-코팅/경기도-과천시/", province: "경기도", region: "과천시", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "과천 바닥왁스코팅",
    body: "지식산업센터 바닥까지 날린 붉은 페인트를 제거하면서 3명이 7시간 동안 왁스코팅까지 진행한 기록입니다.",
    cta: "과천 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional-wax/gwacheon/01-red-paint-before.webp", "/images/regional-wax/gwacheon/06-wax-after.webp"], "과천 지식산업센터 페인트 제거와 바닥왁스코팅"),
  },
  {
    href: "/인테리어청소/경기도-과천시/", province: "경기도", region: "과천시", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "과천 인테리어청소",
    body: "술집 주방의 기름때와 흡연실 니코틴 오염을 확인하며 3명이 9시간 동안 작업한 기록입니다.",
    cta: "과천 술집 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/gwacheon-interior/02-kitchen-floor-before.webp", "/images/gwacheon-interior/04-kitchen-after.webp"], "과천 술집 인테리어청소"),
  },
  {
    href: "/상가청소/경기도-의왕시/", province: "경기도", region: "의왕시", service: "상가청소",
    eyebrow: caseEyebrow, title: "의왕 상가청소",
    body: "내손동 상가의 공사 분진과 바닥·창가·유리 구역을 나누어 3명이 9시간 동안 복원청소한 기록입니다.",
    cta: "의왕 내손동 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/uiwang-store/01-open-area-before.webp", "/images/uiwang-store/02-open-area-after.webp"], "의왕시 내손동 상가 복원청소"),
  },
  {
    href: "/쓰레기집청소/경기도-안양시/", province: "경기도", region: "안양시", service: "쓰레기집청소",
    eyebrow: caseEyebrow, title: "안양 쓰레기집청소",
    body: "장기간 방치된 만안구 다세대주택에서 4명이 8시간 동안 폐기물 반출부터 청소·냄새 제거·소독까지 진행한 기록입니다. 청소로 해결되지 않은 벽지 얼룩까지 그대로 담았습니다.",
    cta: "안양 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/anyang-trash-house-01.webp", "/images/regional/anyang-trash-house-06.webp"], "안양 만안구 다세대주택 쓰레기집청소"),
  },
  {
    href: "/신축준공청소/경기도-안양시/", province: "경기도", region: "안양시", service: "신축준공청소",
    eyebrow: caseEyebrow, title: "안양 준공청소",
    body: "새 입주 전 명학역 인근 상가를 3명이 6시간 동안 천장·창틀·유리 칸막이 양면·바닥까지 청소한 기록입니다.",
    cta: "안양 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/anyang-completion-02.webp", "/images/regional/anyang-completion-09.webp"], "안양 명학역 인근 상가 준공청소"),
  },
  {
    href: "/신축준공청소/경기도-안산시/", province: "경기도", region: "안산시", service: "신축준공청소",
    eyebrow: caseEyebrow, title: "안산 준공청소",
    body: "상록구 한대앞역 인근 20평 복층 식당 옥된장을 2명이 8시간 동안 지붕구조 분진 제거부터 정문 유리까지 청소한 기록입니다.",
    cta: "안산 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/ansan-shop-02.webp", "/images/regional/ansan-shop-11.webp"], "안산 상록구 옥된장 준공청소"),
  },
  {
    href: "/바닥-본드-제거/경기도-안산시/", province: "경기도", region: "안산시", service: "바닥본드제거",
    eyebrow: caseEyebrow, title: "안산 바닥본드제거",
    body: "단원구 상가건물 계단에서 카펫을 걷어낸 뒤 남은 본드를 2~3명이 8시간 동안 제거하고 세척까지 마친 기록입니다.",
    cta: "안산 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/ansan-bond-01.webp", "/images/regional/ansan-bond-06.webp"], "안산 단원구 상가 계단 본드제거"),
  },
  {
    href: "/신축준공청소/경기도-의왕시/", province: "경기도", region: "의왕시", service: "신축준공청소",
    eyebrow: caseEyebrow, title: "의왕 준공청소",
    body: "청계동 골프연습장을 3~4명이 8시간 동안 보양재 제거부터 수납장·콘센트 주변·바닥까지 정리한 준공청소 기록입니다.",
    cta: "의왕 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/uiwang-golf-02.webp", "/images/regional/uiwang-golf-10.webp"], "의왕 청계동 골프연습장 준공청소"),
  },
  {
    href: "/신축준공청소/경기도-군포시/", province: "경기도", region: "군포시", service: "신축준공청소",
    eyebrow: caseEyebrow, title: "군포 준공청소",
    body: "송정지구 피트니스센터를 3~4명이 8시간 동안 바닥 시멘트 얼룩 제거부터 샤워실·사물함·외창까지 정리한 준공청소 기록입니다.",
    cta: "군포 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gunpo-gym-01.webp", "/images/regional/gunpo-gym-07.webp"], "군포 송정지구 피트니스센터 준공청소"),
  },
  {
    href: "/신축준공청소/경기도-수원시/", province: "경기도", region: "수원시", service: "신축준공청소",
    eyebrow: caseEyebrow, title: "수원 준공청소",
    body: "인계동 카페를 3~4명이 8시간 동안 바닥 시멘트 자국 제거부터 벽 타일·전기 분전반·유리까지 정리한 준공청소 기록입니다.",
    cta: "수원 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/suwon-cafe-01.webp", "/images/regional/suwon-cafe-09.webp"], "수원 인계동 카페 준공청소"),
  },
  {
    href: "/신축준공청소/경기도-용인시/", province: "경기도", region: "용인시", service: "신축준공청소",
    eyebrow: caseEyebrow, title: "용인 준공청소",
    body: "수지구 오피스를 3~4명이 8시간 동안 바닥 타일 이음새부터 창틀·환기 필터·소화기까지 정리한 준공청소 기록입니다.",
    cta: "용인 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yongin-office-01.webp", "/images/regional/yongin-office-09.webp"], "용인 수지구 오피스 준공청소"),
  },
  {
    href: "/바닥-본드-제거/경기도-용인시/", province: "경기도", region: "용인시", service: "바닥본드제거",
    eyebrow: caseEyebrow, title: "용인 바닥본드제거",
    body: "수지구 상가 로비 화강암 바닥에 남은 본드를 2~3명이 8시간 동안 바닥광택기와 스크래퍼로 제거하고 세척까지 마친 기록입니다.",
    cta: "용인 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yongin-bond-01.webp", "/images/regional/yongin-bond-06.webp"], "용인 수지구 상가 바닥본드제거"),
  },
  {
    href: "/쓰레기집청소/경기도-군포시/", province: "경기도", region: "군포시", service: "쓰레기집청소",
    eyebrow: caseEyebrow, title: "군포 쓰레기집청소",
    body: "기숙사로 쓰던 산본 아파트의 방 한 칸에서 3명이 8시간 동안 폐기물 처리부터 오염 제거·냄새 제거·소독까지 진행한 기록입니다. 교체가 필요했던 합지 벽지까지 그대로 담았습니다.",
    cta: "군포 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gunpo-trash-house-01.webp", "/images/regional/gunpo-trash-house-07.webp"], "군포 산본 아파트 쓰레기집청소"),
  },
  {
    href: "/인테리어청소/경기도-군포시/", province: "경기도", region: "군포시", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "군포 인테리어청소",
    body: "산본 중심상가 빌딩의 코인노래방을 인테리어 공사 후 3명이 12시간 동안 방마다 스피커·창틀·집기·TV까지 공사 잔재를 걷어내고 청소한 기록입니다.",
    cta: "군포 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gunpo-interior-01.webp", "/images/regional/gunpo-interior-12.webp"], "군포 산본 코인노래방 인테리어청소"),
  },
  {
    href: "/바닥-왁스-코팅/경기도-군포시/", province: "경기도", region: "군포시", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "군포 바닥왁스코팅",
    body: "산본동 70평 가라오케의 검정 데코타일 바닥을 3명이 7시간 동안 정기 관리 차원에서 연마·세척하고 첫 코팅까지 마친 기록입니다. 쉬는 날 낮 시간에 진행해 영업에 지장이 없었습니다.",
    cta: "군포 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gunpo-floor-wax-02.webp", "/images/regional/gunpo-floor-wax-11.webp"], "군포 산본동 가라오케 바닥왁스코팅"),
  },
  {
    href: "/사무실청소/경기도-군포시/", province: "경기도", region: "군포시", service: "사무실청소",
    eyebrow: caseEyebrow, title: "군포 사무실청소",
    body: "당동 지식산업센터 50평 사무실을 인테리어 공사 직후 새벽 안에 4명이 8시간 동안 입주청소한 기록입니다. 사무실 앞 공동복도까지 공사 잔재가 심해 함께 청소했습니다.",
    cta: "군포 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gunpo-office-01.webp", "/images/regional/gunpo-office-13.webp"], "군포 당동 지식산업센터 사무실청소"),
  },
  {
    href: "/쓰레기집청소/경기도-안산시/", province: "경기도", region: "안산시", service: "쓰레기집청소",
    eyebrow: caseEyebrow, title: "안산 쓰레기집청소",
    body: "날파리가 생긴 상록구 원룸을 가족 방문 전에 4명이 3시간 동안 폐기물 처리부터 오염 제거·냄새 제거·소독까지 진행한 기록입니다.",
    cta: "안산 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/ansan-trash-house-04.webp", "/images/regional/ansan-trash-house-13.webp"], "안산 상록구 원룸 쓰레기집청소"),
  },
  {
    href: "/바닥-왁스-코팅/경기도-안산시/", province: "경기도", region: "안산시", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "안산 바닥왁스코팅",
    body: "단원구 30평 물류회사 사무실의 회색 디럭스타일 바닥을 3명이 8시간 동안 유리창·칸막이 샷시 청소와 선반 오일스텐까지 함께 마무리하고 코팅한 기록입니다.",
    cta: "안산 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/ansan-floor-wax-01.webp", "/images/regional/ansan-floor-wax-12.webp"], "안산 단원구 사무실 바닥왁스코팅"),
  },
  {
    href: "/인테리어청소/경기도-안산시/", province: "경기도", region: "안산시", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "안산 인테리어청소",
    body: "인테리어 공사를 마친 상록구 상가의 홀과 주방을 3명이 7시간 동안 짐 이동부터 주방 2명·홀 1명으로 나눠 청소한 기록입니다.",
    cta: "안산 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/ansan-interior-02.webp", "/images/regional/ansan-interior-10.webp"], "안산 상록구 상가 인테리어청소"),
  },
  {
    href: "/공장청소/경기도-시흥시/", province: "경기도", region: "시흥시", service: "공장청소",
    eyebrow: caseEyebrow, title: "시흥 공장청소",
    body: "HACCP 재심사를 앞둔 150평 빵공장을 9명이 빵 랙·벽면·천장·기계·쟁반까지 구역을 나눠 청소한 기록입니다.",
    cta: "시흥 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/siheung-factory-01.webp", "/images/regional/siheung-factory-15.webp"], "시흥 은계지구 빵공장 청소"),
  },
  {
    href: "/화재청소/인천광역시-검단구/", province: "인천광역시", region: "검단구", service: "화재청소",
    eyebrow: caseEyebrow, title: "인천 검단구 화재청소",
    body: "검단 상가건물에서 탄 잔해 반출부터 고소작업대를 이용한 천장 그을음 제거, 바닥 세척까지 진행한 기록입니다.",
    cta: "인천 검단구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/geomdan-fire-01.webp", "/images/regional/geomdan-fire-09.webp"], "인천 검단구 상가건물 화재청소"),
  },
  {
    href: "/쓰레기집청소/인천광역시-검단구/", province: "인천광역시", region: "검단구", service: "쓰레기집청소",
    eyebrow: caseEyebrow, title: "인천 검단구 쓰레기집청소",
    body: "방과 주방을 채운 폐기물을 트럭으로 반출하고 바닥·욕실·주방 오염까지 정리한 빌라 원룸 기록입니다.",
    cta: "인천 검단구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/geomdan-trash-01.webp", "/images/regional/geomdan-trash-09.webp"], "인천 검단구 빌라 원룸 쓰레기집청소"),
  },
  {
    href: "/화재청소/인천광역시-남동구/", province: "인천광역시", region: "남동구", service: "화재청소",
    eyebrow: caseEyebrow, title: "인천 남동구 화재청소",
    body: "남동공단 공장에서 생산 설비를 보양한 뒤 고소 장비로 천장과 벽의 그을음을 세척한 기록입니다.",
    cta: "인천 남동구 사례와 견적 기준 보기",
    photos: pair(["작업 준비", "작업 중"] as const, ["/images/regional/namdong-fire-01.webp", "/images/regional/namdong-fire-04.webp"], "인천 남동공단 공장 화재청소"),
  },
  {
    href: "/쓰레기집청소/인천광역시-남동구/", province: "인천광역시", region: "남동구", service: "쓰레기집청소",
    eyebrow: caseEyebrow, title: "인천 남동구 쓰레기집청소",
    body: "바닥을 덮은 생활 쓰레기와 옷가지를 치우고 변기·창틀까지 정리한 구월동 원룸 기록입니다.",
    cta: "인천 남동구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/namdong-trash-01.webp", "/images/regional/namdong-trash-08.webp"], "인천 남동구 구월동 원룸 쓰레기집청소"),
  },
  {
    href: "/바닥-왁스-코팅/인천광역시-남동구/", province: "인천광역시", region: "남동구", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "인천 남동구 바닥왁스코팅",
    body: "영업을 마친 객장 바닥을 박리·세척하고 2회 코팅하면서 조명 커버와 의자까지 정리한 기록입니다.",
    cta: "인천 남동구 사례와 견적 기준 보기",
    photos: pair(["작업 중", "작업 후"] as const, ["/images/regional/namdong-floor-wax-01.webp", "/images/regional/namdong-floor-wax-06.webp"], "인천 남동구 구월동 영업점 바닥왁스코팅"),
  },
  {
    href: "/화재청소/인천광역시-부평구/", province: "인천광역시", region: "부평구", service: "화재청소",
    eyebrow: caseEyebrow, title: "인천 부평구 화재청소",
    body: "부평역 상권 상가 뒤편 창고에서 탄 짐과 폐기물을 반출하고 통로를 정리한 기록입니다.",
    cta: "인천 부평구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/bupyeong-fire-01.webp", "/images/regional/bupyeong-fire-02.webp"], "인천 부평역 상가 창고 화재청소"),
  },
  {
    href: "/쓰레기집청소/인천광역시-부평구/", province: "인천광역시", region: "부평구", service: "쓰레기집청소",
    eyebrow: caseEyebrow, title: "인천 부평구 쓰레기집청소",
    body: "짐과 쓰레기가 쌓인 오피스텔을 정리하고 세면대·욕실·냉장고까지 닦은 기록입니다.",
    cta: "인천 부평구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/bupyeong-trash-03.webp", "/images/regional/bupyeong-trash-07.webp"], "인천 부평역 오피스텔 쓰레기집청소"),
  },
  {
    href: "/화재청소/인천광역시-미추홀구/", province: "인천광역시", region: "미추홀구", service: "화재청소",
    eyebrow: caseEyebrow, title: "인천 미추홀구 화재청소",
    body: "주안 상가건물 층 전체에서 천장·창틀·선반의 그을음을 닦고 바닥 세척까지 진행한 기록입니다.",
    cta: "인천 미추홀구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/michuhol-fire-01.webp", "/images/regional/michuhol-fire-11.webp"], "인천 주안 상가건물 화재청소"),
  },
  {
    href: "/쓰레기집청소/인천광역시-미추홀구/", province: "인천광역시", region: "미추홀구", service: "쓰레기집청소",
    eyebrow: caseEyebrow, title: "인천 미추홀구 쓰레기집청소",
    body: "페트병과 박스가 쌓인 방과 오물로 오염된 욕실을 정리하고 소독까지 마친 주안 원룸 기록입니다.",
    cta: "인천 미추홀구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/michuhol-trash-01.webp", "/images/regional/michuhol-trash-09.webp"], "인천 주안 원룸 쓰레기집청소"),
  },
  {
    href: "/고독사청소/인천광역시-미추홀구/", province: "인천광역시", region: "미추홀구", service: "고독사청소",
    eyebrow: caseEyebrow, title: "인천 미추홀구 고독사청소",
    body: "다세대주택에서 사다리차로 가구와 물품을 반출하고 오염된 장판과 주방 벽을 걷어낸 뒤 소독까지 마친 기록입니다.",
    cta: "인천 미추홀구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/michuhol-lonely-01.webp", "/images/regional/michuhol-lonely-10.webp"], "인천 미추홀구 다세대주택 고독사청소"),
  },
  {
    href: "/바닥-왁스-코팅/인천광역시-미추홀구/", province: "인천광역시", region: "미추홀구", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "인천 미추홀구 바닥왁스코팅",
    body: "학교 복도와 교실, 나무 바닥을 박리·세척하고 2회 코팅한 기록입니다.",
    cta: "인천 미추홀구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/michuhol-floor-wax-01.webp", "/images/regional/michuhol-floor-wax-11.webp"], "인천 미추홀구 학교 바닥왁스코팅"),
  },
  {
    href: "/화재청소/인천광역시-연수구/", province: "인천광역시", region: "연수구", service: "화재청소",
    eyebrow: caseEyebrow, title: "인천 연수구 화재청소",
    body: "송도 오피스에서 책상·컴퓨터 주변과 사무실·복도 바닥에 내려앉은 그을음을 제거한 기록입니다.",
    cta: "인천 연수구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/songdo-fire-01.webp", "/images/regional/songdo-fire-11.webp"], "인천 송도 오피스 화재청소"),
  },
  {
    href: "/쓰레기집청소/인천광역시-연수구/", province: "인천광역시", region: "연수구", service: "쓰레기집청소",
    eyebrow: caseEyebrow, title: "인천 연수구 쓰레기집청소",
    body: "방과 욕실, 선반까지 쌓인 짐과 쓰레기를 치우고 세면대·수납장·창틀까지 닦은 송도 오피스텔 기록입니다.",
    cta: "인천 연수구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/songdo-trash-01.webp", "/images/regional/songdo-trash-12.webp"], "인천 송도 오피스텔 쓰레기집청소"),
  },
  {
    href: "/바닥-왁스-코팅/경기도-수원시/", province: "경기도", region: "수원시", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "수원 바닥왁스코팅",
    body: "오랫동안 청소하지 않아 오염과 테이프 자국이 많던 영통 사무실 입구와 회의실을 2명이 6시간 동안 세척하고 2회 코팅한 기록입니다. 작업 영상도 함께 담았습니다.",
    cta: "수원 사례와 견적 기준 보기",
    photos: pair(["세척 중", "코팅 후"], ["/images/regional/suwon-floor-wax-01.webp", "/images/regional/suwon-floor-wax-04.webp"], "수원 영통 사무실 바닥왁스코팅"),
  },
  {
    href: "/사무실청소/경기도-수원시-영통구/", province: "경기도", region: "수원시", service: "사무실청소",
    eyebrow: caseEyebrow, title: "수원 영통구 사무실청소",
    body: "인테리어 공사를 마친 50평 신축 사무실을 3명이 8시간 동안 천장부터 유리·창틀, 탕비실·수납장, 바닥 코팅까지 청소한 입주 전 기록입니다.",
    cta: "영통구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/suwon-office-01.webp", "/images/regional/suwon-office-10.webp"], "수원 영통구 사무실청소"),
  },
  {
    href: "/인테리어청소/경기도-수원시-영통구/", province: "경기도", region: "수원시", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "수원 영통구 인테리어청소",
    body: "인테리어 공사를 마친 영통구 35평 아파트를 4명이 8시간 동안 창틀 사이 좁은 틈의 분진과 욕실 백색시멘트까지 제거하고 마무리한 기록입니다.",
    cta: "수원 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/suwon-interior-02.webp", "/images/regional/suwon-interior-05.webp"], "수원 영통구 아파트 인테리어청소"),
  },
  {
    href: "/바닥-왁스-코팅/경기도-용인시/", province: "경기도", region: "용인시", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "용인 바닥왁스코팅",
    body: "5년 만에 관리한 수지구 교회 예배당 200평 데코타일 바닥을 6명이 장의자를 옮기며 박리하고 2회 코팅한 기록입니다. 작업 영상도 함께 담았습니다.",
    cta: "용인 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yongin-floor-wax-03.webp", "/images/regional/yongin-floor-wax-10.webp"], "용인 수지구 교회 바닥왁스코팅"),
  },
  {
    href: "/인테리어청소/경기도-용인시/", province: "경기도", region: "용인시", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "용인 인테리어청소",
    body: "인테리어 공사를 마친 수지구 62평 타운하우스를 7명이 8시간 동안 보양지 제거부터 천장 도배풀, 벽지·집기·바닥까지 청소한 입주 전 기록입니다.",
    cta: "용인 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yongin-interior-02.webp", "/images/regional/yongin-interior-12.webp"], "용인 수지구 타운하우스 인테리어청소"),
  },
  {
    href: "/사무실청소/경기도-의왕시/", province: "경기도", region: "의왕시", service: "사무실청소",
    eyebrow: caseEyebrow, title: "의왕 사무실청소",
    body: "새로 준공된 부곡동 지식산업센터 250평 사무실을 8명이 8시간 동안 천장 에어컨 디퓨저부터 유리·창틀, 시스템박스·배전반, 바닥까지 청소한 입주 전 기록입니다.",
    cta: "의왕 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/uiwang-office-01.webp", "/images/regional/uiwang-office-12.webp"], "의왕 부곡동 지식산업센터 사무실청소"),
  },
  {
    href: "/바닥-왁스-코팅/경기도-의왕시/", province: "경기도", region: "의왕시", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "의왕 바닥왁스코팅",
    body: "내손동 10평 음식점의 바닥을 2명이 4시간 동안 기름때를 제거하고 첫 코팅까지 마친 기록입니다.",
    cta: "의왕 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/uiwang-floor-wax-02.webp", "/images/regional/uiwang-floor-wax-11.webp"], "의왕 내손동 음식점 바닥왁스코팅"),
  },
  {
    href: "/인테리어청소/경기도-양주시/", province: "경기도", region: "양주시", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "양주 인테리어청소",
    body: "레드랩 댄스스튜디오의 높은 천장 에어컨과 스피커를 LS 사다리로 청소하고, 푹신한 바닥에 자국이 남지 않도록 사다리 접촉 부분을 보호하며 4명이 8시간 작업한 기록입니다.",
    cta: "양주 사례와 견적 기준 보기",
    photos: pair(["현장 사진", "작업 기록"] as const, ["/images/interior-cases/yangju/03-studio.webp", "/images/interior-cases/yangju/05-speaker.webp"], "양주 레드랩 댄스스튜디오 인테리어청소"),
  },
  {
    href: "/인테리어청소/경기도-남양주시/", province: "경기도", region: "남양주시 화도읍", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "화도읍 인테리어청소",
    body: "카페의 범위가 넓은 천장 인테리어 조형물과 실내, 옥상까지 3명이 9시간 동안 청소한 기록입니다.",
    cta: "화도읍 사례와 견적 기준 보기",
    photos: pair(["천장 조형물", "옥상"] as const, ["/images/interior-cases/hwado/02-ceiling-structure.webp", "/images/interior-cases/hwado/05-rooftop.webp"], "남양주 화도읍 카페 인테리어청소"),
  },
  {
    href: "/인테리어청소/서울특별시-서초구/", province: "서울특별시", region: "서초구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "서초 인테리어청소",
    body: "스튜디오 내부의 많은 짐을 옮겨가며 작업 구역을 확보해 4명이 8시간 동안 청소한 기록입니다.",
    cta: "서초 사례와 견적 기준 보기",
    photos: pair(["작업 전", "작업 기록"] as const, ["/images/interior-cases/seocho/02-stored-items.webp", "/images/interior-cases/seocho/06-equipment-area.webp"], "서초 스튜디오 인테리어청소"),
  },
  {
    href: "/인테리어청소/경기도-화성시-동탄구/", province: "경기도", region: "화성시 동탄구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "동탄 인테리어청소",
    body: "BAR 내부의 큰 고급 주류병을 모두 치우고, 일반 분리수거가 어려운 병을 폐기물 처리로 마무리하며 3명이 8시간 작업한 기록입니다.",
    cta: "동탄 사례와 견적 기준 보기",
    photos: pair(["반출 준비", "현장 사진"] as const, ["/images/interior-cases/dongtan/05-bottles.webp", "/images/interior-cases/dongtan/06-shelves.webp"], "동탄 BAR 인테리어청소"),
  },
  {
    href: "/고독사청소/경기도-수원시/", province: "경기도", region: "수원시", service: "고독사청소",
    eyebrow: caseEyebrow, title: "수원 고독사청소",
    body: "가정집 바닥에 남은 옷가지와 생활용품, 냉장고 음식물을 수거하고 방과 주방, 베란다를 비운 기록입니다.",
    cta: "수원 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/suwon-lonely-01.webp", "/images/regional/suwon-lonely-06.webp"], "수원 가정집 고독사청소"),
  },
  {
    href: "/유품정리/경기도-안산시/", province: "경기도", region: "안산시", service: "유품정리",
    eyebrow: caseEyebrow, title: "안산 유품정리",
    body: "원룸에 남은 생활용품과 보일러실 짐을 분류해 수거하고 주방과 창틀까지 닦아 비운 기록입니다.",
    cta: "안산 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/ansan-legacy-01.webp", "/images/regional/ansan-legacy-09.webp"], "안산 원룸 유품정리"),
  },
  {
    href: "/고독사청소/경기도-이천시/", province: "경기도", region: "이천시", service: "고독사청소",
    eyebrow: caseEyebrow, title: "이천 고독사청소",
    body: "원룸 바닥의 물품을 수거하고 오염된 바닥재를 걷어낸 뒤 벽면 소독과 주방 세척까지 진행한 기록입니다.",
    cta: "이천 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/icheon-lonely-02.webp", "/images/regional/icheon-lonely-05.webp"], "이천 원룸 고독사청소"),
  },
  {
    href: "/고독사청소/경기도-부천시/", province: "경기도", region: "부천시", service: "고독사청소",
    eyebrow: caseEyebrow, title: "부천 고독사청소",
    body: "아파트 바닥과 베란다, 수납장, 욕실, 창틀까지 작업 전에 오염 범위를 하나씩 확인한 기록입니다.",
    cta: "부천 사례와 견적 기준 보기",
    photos: pair(["작업 전 확인", "작업 전 확인"] as const, ["/images/regional/bucheon-lonely-01.webp", "/images/regional/bucheon-lonely-02.webp"], "부천 아파트 고독사청소 오염 확인"),
  },
  {
    href: "/고독사청소/서울특별시-도봉구/", province: "서울특별시", region: "도봉구", service: "고독사청소",
    eyebrow: caseEyebrow, title: "서울 도봉구 고독사청소",
    body: "다세대주택 원룸에서 물품을 분류해 수거하고 곰팡이가 번진 벽면을 닦은 뒤 주방과 욕실까지 정리한 기록입니다.",
    cta: "도봉구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/dobong-lonely-01.webp", "/images/regional/dobong-lonely-09.webp"], "서울 도봉구 다세대주택 원룸 고독사청소"),
  },
  {
    href: "/유품정리/서울특별시-용산구/", province: "서울특별시", region: "용산구", service: "유품정리",
    eyebrow: caseEyebrow, title: "서울 용산구 유품정리",
    body: "주택에 남은 장롱과 옷가지, 생활용품을 정리하고 가구를 해체해 반출한 뒤 바닥 청소까지 마친 기록입니다.",
    cta: "용산구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yongsan-legacy-01.webp", "/images/regional/yongsan-legacy-10.webp"], "서울 용산구 주택 유품정리"),
  },
  {
    href: "/바닥-왁스-코팅/서울특별시-서초구/", province: "서울특별시", region: "서초구", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "서울 서초구 바닥왁스코팅",
    body: "사무실 창문 시트지를 제거하고 얼룩진 바닥을 장비로 세척한 뒤 왁스를 코팅한 기록입니다.",
    cta: "서초구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/seocho-floor-wax-02.webp", "/images/regional/seocho-floor-wax-12.webp"], "서울 서초구 사무실 바닥왁스코팅"),
  },
  {
    href: "/바닥-왁스-코팅/서울특별시-송파구/", province: "서울특별시", region: "송파구", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "서울 송파구 바닥왁스코팅",
    body: "넓은 사무 공간의 기존 왁스를 장비로 박리하고 잔여물을 걷어낸 뒤 새로 코팅한 기록입니다.",
    cta: "송파구 사례와 견적 기준 보기",
    photos: pair(["작업 전", "코팅 중"] as const, ["/images/regional/songpa-floor-wax-01.webp", "/images/regional/songpa-floor-wax-10.webp"], "서울 송파구 사무 공간 바닥왁스코팅"),
  },
  {
    href: "/바닥-왁스-코팅/서울특별시-구로구/", province: "서울특별시", region: "구로구", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "서울 구로구 바닥왁스코팅",
    body: "사무실 바닥을 장비로 세척하고 유리 파티션 아래 가장자리까지 정리한 뒤 왁스를 코팅한 기록입니다.",
    cta: "구로구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/guro-floor-wax-01.webp", "/images/regional/guro-floor-wax-11.webp"], "서울 구로구 사무실 바닥왁스코팅"),
  },
  {
    href: "/바닥-왁스-코팅/서울특별시-강남구/", province: "서울특별시", region: "강남구", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "서울 강남구 바닥왁스코팅",
    body: "파티션 사이와 집기 자리에 얼룩이 번진 사무실 바닥을 장비로 세척하고 왁스를 코팅한 기록입니다.",
    cta: "강남구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gangnam-floor-wax-01.webp", "/images/regional/gangnam-floor-wax-09.webp"], "서울 강남구 사무실 바닥왁스코팅"),
  },
  {
    href: "/바닥-왁스-코팅/서울특별시-동대문구/", province: "서울특별시", region: "동대문구", service: "바닥왁스코팅",
    eyebrow: caseEyebrow, title: "서울 동대문구 바닥왁스코팅",
    body: "병원 대기실·복도의 포세린 타일과 진료실 데코타일을 바닥재별로 세척하고 코팅한 기록입니다.",
    cta: "동대문구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/dongdaemun-floor-wax-03.webp", "/images/regional/dongdaemun-floor-wax-14.webp"], "서울 동대문구 병원 바닥왁스코팅"),
  },
  {
    href: "/인테리어청소/서울특별시-성동구/", province: "서울특별시", region: "성동구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "서울 성동구 인테리어청소",
    body: "음식점 홀과 화장실, 창고, 주방을 공간별로 나눠 공사 후 청소한 기록입니다.",
    cta: "성동구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/seongdong-interior-01.webp", "/images/regional/seongdong-interior-12.webp"], "서울 성동구 음식점 인테리어청소"),
  },
  {
    href: "/인테리어청소/서울특별시-강남구/", province: "서울특별시", region: "강남구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "서울 강남구 인테리어청소",
    body: "피부과 유리 파티션의 표시 테이프를 정리하고 진료실과 복도를 청소한 기록입니다.",
    cta: "강남구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gangnam-interior-01.webp", "/images/regional/gangnam-interior-10.webp"], "서울 강남구 피부과 인테리어청소"),
  },
  {
    href: "/인테리어청소/서울특별시-종로구/", province: "서울특별시", region: "종로구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "서울 종로구 인테리어청소",
    body: "그릇 매장의 유리 진열장과 목재 선반, 통로 바닥을 칸마다 청소한 기록입니다.",
    cta: "종로구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/jongno-interior-03.webp", "/images/regional/jongno-interior-11.webp"], "서울 종로구 그릇 매장 인테리어청소"),
  },
  {
    href: "/인테리어청소/서울특별시-성북구/", province: "서울특별시", region: "성북구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "서울 성북구 인테리어청소",
    body: "자재와 쓰레기가 흩어진 음식점 홀을 정리하고 카운터와 주방까지 청소한 기록입니다.",
    cta: "성북구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/seongbuk-interior-01.webp", "/images/regional/seongbuk-interior-04.webp"], "서울 성북구 음식점 인테리어청소"),
  },
  {
    href: "/인테리어청소/서울특별시-은평구/", province: "서울특별시", region: "은평구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "서울 은평구 인테리어청소",
    body: "음식점의 복도와 창고, 천장 설비 아래 넓은 홀 바닥을 청소한 기록입니다.",
    cta: "은평구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/eunpyeong-interior-02.webp", "/images/regional/eunpyeong-interior-07.webp"], "서울 은평구 음식점 인테리어청소"),
  },
  {
    href: "/인테리어청소/서울특별시-금천구/", province: "서울특별시", region: "금천구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "서울 금천구 인테리어청소",
    body: "카페 바 주방 설비와 에어컨 필터, 홀 바닥을 오픈 전에 청소한 기록입니다.",
    cta: "금천구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/geumcheon-interior-01.webp", "/images/regional/geumcheon-interior-05.webp"], "서울 금천구 카페 인테리어청소"),
  },
  {
    href: "/인테리어청소/서울특별시-강동구/", province: "서울특별시", region: "강동구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "서울 강동구 인테리어청소",
    body: "한의원 창호 유리의 스티커와 창틀 분진을 정리하고 진료실과 복도를 청소한 기록입니다.",
    cta: "강동구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gangdong-interior-06.webp", "/images/regional/gangdong-interior-09.webp"], "서울 강동구 한의원 인테리어청소"),
  },
  {
    href: "/인테리어청소/서울특별시-용산구/", province: "서울특별시", region: "용산구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "서울 용산구 인테리어청소",
    body: "음식점 화장실 분진과 오픈 주방 설비, 홀 바닥과 창가를 청소한 기록입니다.",
    cta: "용산구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yongsan-interior-03.webp", "/images/regional/yongsan-interior-06.webp"], "서울 용산구 음식점 인테리어청소"),
  },
  {
    href: "/인테리어청소/경기도-의정부시/", province: "경기도", region: "의정부시", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "의정부 인테리어청소",
    body: "병원 수납장과 사물함 안쪽, 싱크대 하부장 분진과 진료실 바닥을 청소한 기록입니다.",
    cta: "의정부 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/uijeongbu-interior-02.webp", "/images/regional/uijeongbu-interior-05.webp"], "경기 의정부 병원 인테리어청소"),
  },
  {
    href: "/인테리어청소/경기도-부천시/", province: "경기도", region: "부천시", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "부천 인테리어청소",
    body: "상가 벽면과 화장실, 전면 유리창과 창틀을 공사 후 청소한 기록입니다.",
    cta: "부천 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/bucheon-interior-03.webp", "/images/regional/bucheon-interior-05.webp"], "경기 부천 상가 인테리어청소"),
  },
  {
    href: "/화재청소/경기도-김포시/", province: "경기도", region: "김포시", service: "화재청소",
    eyebrow: caseEyebrow, title: "김포 화재청소",
    body: "화재 후 음식점 주방 벽면과 선반, 작업대, 후드 필터를 함께 청소한 기록입니다.",
    cta: "김포 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gimpo-fire-08.webp", "/images/regional/gimpo-fire-17.webp"], "김포 음식점 주방 화재청소"),
  },
  {
    href: "/쓰레기집청소/경기도-의정부시/", province: "경기도", region: "의정부시", service: "쓰레기집청소",
    eyebrow: caseEyebrow, title: "의정부 쓰레기집청소",
    body: "아파트에 쌓인 짐을 반출하고 주방 바닥과 베란다, 창틀의 오염을 청소한 기록입니다.",
    cta: "의정부 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/uijeongbu-trash-house-06.webp", "/images/regional/uijeongbu-trash-house-13.webp"], "의정부 아파트 쓰레기집청소"),
  },
  {
    href: "/행사장청소/서울특별시-송파구/", province: "서울특별시", region: "송파구", service: "행사장청소",
    eyebrow: caseEyebrow, title: "서울 송파구 행사장청소",
    body: "공원 광장 행사가 끝난 뒤 흩어진 쓰레기와 물품을 야간에 정리한 기록입니다.",
    cta: "송파구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/songpa-event-01.webp", "/images/regional/songpa-event-08.webp"], "서울 송파구 공원 광장 행사장청소"),
  },
  {
    href: "/사무실청소/서울특별시-강남구/", province: "서울특별시", region: "강남구", service: "사무실청소",
    eyebrow: caseEyebrow, title: "서울 강남구 사무실청소",
    body: "공사를 마친 사무실의 천장 그릴과 창틀 레일, 수납장과 화장실, 바닥까지 입주 전에 청소한 기록입니다.",
    cta: "강남구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/nonhyeon-office-01.webp", "/images/regional/nonhyeon-office-08.webp"], "서울 강남구 사무실청소"),
  },
  {
    href: "/사무실청소/경기도-고양시/", province: "경기도", region: "고양시", service: "사무실청소",
    eyebrow: caseEyebrow, title: "고양 사무실청소",
    body: "일산 복층 신축 사무실의 보와 천장 배관 위 먼지를 걷어내고 바닥과 탕비 공간까지 청소한 기록입니다.",
    cta: "고양 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/ilsan-office-03.webp", "/images/regional/ilsan-office-11.webp"], "고양 일산 사무실청소"),
  },
  {
    href: "/사무실청소/서울특별시-서초구/", province: "서울특별시", region: "서초구", service: "사무실청소",
    eyebrow: caseEyebrow, title: "서울 서초구 사무실청소",
    body: "4층 건물의 계단과 화장실, 층별 홀 바닥을 동선을 나눠 청소한 기록입니다.",
    cta: "서초구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/jamwon-office-02.webp", "/images/regional/jamwon-office-07.webp"], "서울 서초구 건물 사무실청소"),
  },
  {
    href: "/사무실청소/서울특별시-종로구/", province: "서울특별시", region: "종로구", service: "사무실청소",
    eyebrow: caseEyebrow, title: "서울 종로구 사무실청소",
    body: "천장 디퓨저와 창가 그릴을 분리해 닦고 조명과 사무실 바닥까지 청소한 기록입니다.",
    cta: "종로구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/jongno-office-04.webp", "/images/regional/jongno-office-08.webp"], "서울 종로구 사무실청소"),
  },
  {
    href: "/사무실청소/인천광역시-서해구/", province: "인천광역시", region: "서해구", service: "사무실청소",
    eyebrow: caseEyebrow, title: "인천 서해구 사무실청소",
    body: "청라 사무실의 블라인드와 스위치, 창틀을 닦고 넓은 바닥까지 청소한 기록입니다.",
    cta: "서해구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/cheongna-office-01.webp", "/images/regional/cheongna-office-04.webp"], "인천 서해구 사무실청소"),
  },
  {
    href: "/사무실청소/경기도-안양시/", province: "경기도", region: "안양시", service: "사무실청소",
    eyebrow: caseEyebrow, title: "안양 사무실청소",
    body: "평촌 지식산업센터 사무실의 창가 턱과 바닥 콘센트 박스, 복도와 방 바닥을 입주 전에 청소한 기록입니다.",
    cta: "안양 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/pyeongchon-office-01.webp", "/images/regional/pyeongchon-office-09.webp"], "안양 평촌 지식산업센터 사무실청소"),
  },
  {
    href: "/사무실청소/서울특별시-용산구/", province: "서울특별시", region: "용산구", service: "사무실청소",
    eyebrow: caseEyebrow, title: "서울 용산구 사무실청소",
    body: "2층 주택 사무실의 주방과 환풍기, 창틀, 붙박이 수납장까지 청소한 기록입니다.",
    cta: "용산구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/hannam-office-02.webp", "/images/regional/hannam-office-07.webp"], "서울 용산구 주택 사무실청소"),
  },
  {
    href: "/사무실청소/경기도-화성시/", province: "경기도", region: "화성시", service: "사무실청소",
    eyebrow: caseEyebrow, title: "화성 사무실청소",
    body: "사무실과 기숙사 건물의 로비와 세면대, 화장실 바닥, 방과 복도를 청소한 기록입니다.",
    cta: "화성 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/hwaseong-office-04.webp", "/images/regional/hwaseong-office-12.webp"], "화성 사무실·기숙사 청소"),
  },
  {
    href: "/인테리어청소/서울특별시-영등포구/", province: "서울특별시", region: "영등포구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "영등포구 인테리어청소",
    body: "약국 진열 선반과 수납장 안쪽, 매장 바닥을 공사 후 청소한 기록입니다.",
    cta: "영등포구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yeouido-interior-02.webp", "/images/regional/yeouido-interior-09.webp"], "서울 영등포구 약국 인테리어청소"),
  },
  {
    href: "/인테리어청소/서울특별시-동대문구/", province: "서울특별시", region: "동대문구", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "동대문구 인테리어청소",
    body: "김밥집 주방 설비 주변과 유리창, 홀 바닥을 공사 후 청소한 기록입니다.",
    cta: "동대문구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/imun-interior-01.webp", "/images/regional/imun-interior-09.webp"], "서울 동대문구 김밥집 인테리어청소"),
  },
  {
    href: "/인테리어청소/경기도-평택시/", province: "경기도", region: "평택시", service: "인테리어청소",
    eyebrow: caseEyebrow, title: "평택 인테리어청소",
    body: "피부과 복도와 진료 공간, 화장실을 공사 후 청소한 기록입니다.",
    cta: "평택 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/pyeongtaek-interior-01.webp", "/images/regional/pyeongtaek-interior-10.webp"], "경기 평택 피부과 인테리어청소"),
  },
  {
    href: "/곰팡이제거/경기도-광주시/", province: "경기도", region: "광주시", service: "곰팡이제거",
    eyebrow: caseEyebrow, title: "경기 광주 곰팡이제거",
    body: "벽지 뒤로 번진 곰팡이를 벽지를 걷어내고 벽면과 천장까지 제거한 기록입니다.",
    cta: "광주 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/gwangju-mold-02.webp", "/images/regional/gwangju-mold-09.webp"], "경기 광주 주택 방 곰팡이제거"),
  },
  {
    href: "/곰팡이제거/경기도-성남시-분당구/", province: "경기도", region: "분당구", service: "곰팡이제거",
    eyebrow: caseEyebrow, title: "분당 곰팡이제거",
    body: "수납장 안쪽과 벽지 모서리, 배관 주변의 곰팡이를 제거한 기록입니다.",
    cta: "분당 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/bundang-mold-04.webp", "/images/regional/bundang-mold-08.webp"], "성남 분당 주택 곰팡이제거"),
  },
  {
    href: "/곰팡이제거/경기도-안양시/", province: "경기도", region: "안양시", service: "곰팡이제거",
    eyebrow: caseEyebrow, title: "안양 곰팡이제거",
    body: "바닥재 아래로 번진 바닥 곰팡이를 걷어낸 기록입니다.",
    cta: "안양 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/anyang-mold-04.webp", "/images/regional/anyang-mold-06.webp"], "안양 주택 곰팡이제거"),
  },
  {
    href: "/곰팡이제거/경기도-용인시/", province: "경기도", region: "용인시", service: "곰팡이제거",
    eyebrow: caseEyebrow, title: "용인 곰팡이제거",
    body: "베란다 벽면 전체와 배관 뒤까지 번진 곰팡이를 제거한 기록입니다.",
    cta: "용인 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yongin-mold-03.webp", "/images/regional/yongin-mold-09.webp"], "용인 베란다 곰팡이제거"),
  },
  {
    href: "/공장청소/경기도-고양시/", province: "경기도", region: "고양시", service: "공장청소",
    eyebrow: caseEyebrow, title: "고양 공장청소",
    body: "HACCP 준비를 위해 식품 공장 선반과 설비, 창틀 먼지를 청소한 기록입니다.",
    cta: "고양 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/ilsan-haccp-03.webp", "/images/regional/ilsan-haccp-11.webp"], "고양 일산 식품 공장 청소"),
  },
  {
    href: "/관공서청소/경기도-용인시/", province: "경기도", region: "용인시", service: "관공서청소",
    eyebrow: caseEyebrow, title: "용인 관공서청소",
    body: "시립 어린이집 창틀과 교실, 화장실과 보일러실을 공사 후 청소한 기록입니다.",
    cta: "용인 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/cheoin-daycare-03.webp", "/images/regional/cheoin-daycare-12.webp"], "용인 처인구 시립 어린이집 청소"),
  },
  {
    href: "/상가청소/서울특별시-서초구/", province: "서울특별시", region: "서초구", service: "상가청소",
    eyebrow: caseEyebrow, title: "서초구 상가청소",
    body: "상가 건물 창틀 레일과 벽면 루버, 천장 냉난방기 주변을 복원 청소한 기록입니다.",
    cta: "서초구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/seocho-restore-03.webp", "/images/regional/seocho-restore-05.webp"], "서울 서초구 상가 건물 복원청소"),
  },
  {
    href: "/신축준공청소/서울특별시-구로구/", province: "서울특별시", region: "구로구", service: "신축준공청소",
    eyebrow: caseEyebrow, title: "구로구 신축준공청소",
    body: "카페 공사 후 바닥 쓰레기와 설비 아래, 수납장 안쪽을 청소한 기록입니다.",
    cta: "구로구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/guro-newbuild-02.webp", "/images/regional/guro-newbuild-09.webp"], "서울 구로구 카페 신축준공청소"),
  },
  {
    href: "/신축준공청소/인천광역시-제물포구/", province: "인천광역시", region: "제물포구", service: "신축준공청소",
    eyebrow: caseEyebrow, title: "제물포구 신축준공청소",
    body: "신포동 상가 공사 후 매장 바닥과 계단, 개수대와 화장실을 청소한 기록입니다.",
    cta: "제물포구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/sinpo-newbuild-04.webp", "/images/regional/sinpo-newbuild-07.webp"], "인천 신포동 상가 신축준공청소"),
  },
  {
    href: "/주방청소/경기도-부천시/", province: "경기도", region: "부천시", service: "주방청소",
    eyebrow: caseEyebrow, title: "부천 주방청소",
    body: "구내식당 주방의 화구와 벽면, 후드 안쪽과 선반까지 청소한 기록입니다.",
    cta: "부천 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/bucheon-kitchen-01.webp", "/images/regional/bucheon-kitchen-06.webp"], "부천 구내식당 주방청소"),
  },
  {
    href: "/주방청소/경기도-수원시/", province: "경기도", region: "수원시", service: "주방청소",
    eyebrow: caseEyebrow, title: "수원 주방청소",
    body: "집기가 쌓인 음식점 주방의 튀김기와 벽면, 홀까지 청소한 기록입니다.",
    cta: "수원 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/suwon-kitchen-03.webp", "/images/regional/suwon-kitchen-10.webp"], "수원 음식점 주방청소"),
  },
  {
    href: "/주방청소/경기도-의정부시/", province: "경기도", region: "의정부시", service: "주방청소",
    eyebrow: caseEyebrow, title: "의정부 주방청소",
    body: "음식점 주방의 후드 안쪽과 배기구, 그리들과 개수대를 청소한 기록입니다.",
    cta: "의정부 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/uijeongbu-kitchen-02.webp", "/images/regional/uijeongbu-kitchen-07.webp"], "의정부 음식점 주방청소"),
  },
  {
    href: "/주방청소/경기도-화성시/", province: "경기도", region: "화성시", service: "주방청소",
    eyebrow: caseEyebrow, title: "화성 주방청소",
    body: "고깃집 주방의 후드 안쪽과 배기 덕트 연결부를 청소한 기록입니다.",
    cta: "화성 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/hwaseong-kitchen-02.webp", "/images/regional/hwaseong-kitchen-10.webp"], "화성 고깃집 주방청소"),
  },
  {
    href: "/주방청소/서울특별시-서초구/", province: "서울특별시", region: "서초구", service: "주방청소",
    eyebrow: caseEyebrow, title: "서울 서초구 주방청소",
    body: "소형 매장의 주방 작업대 주변과 출입구 바닥을 청소한 기록입니다.",
    cta: "서초구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/seocho-kitchen-01.webp", "/images/regional/seocho-kitchen-04.webp"], "서울 서초구 소형 매장 주방청소"),
  },
  {
    href: "/주방청소/서울특별시-영등포구/", province: "서울특별시", region: "영등포구", service: "주방청소",
    eyebrow: caseEyebrow, title: "서울 영등포구 주방청소",
    body: "음식점이 퇴거한 주방의 벽면 기름때와 바닥을 청소한 기록입니다.",
    cta: "영등포구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/daerim-kitchen-02.webp", "/images/regional/daerim-kitchen-08.webp"], "서울 영등포구 음식점 주방청소"),
  },
  {
    href: "/주방청소/인천광역시-미추홀구/", province: "인천광역시", region: "미추홀구", service: "주방청소",
    eyebrow: caseEyebrow, title: "인천 미추홀구 주방청소",
    body: "집기가 흩어진 음식점 홀과 주방을 정리하고 청소한 기록입니다.",
    cta: "미추홀구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/michuhol-kitchen-01.webp", "/images/regional/michuhol-kitchen-10.webp"], "인천 미추홀구 음식점 홀·주방청소"),
  },
  {
    href: "/후드청소/경기도-화성시/", province: "경기도", region: "화성시", service: "후드청소",
    eyebrow: caseEyebrow, title: "화성 후드청소",
    body: "어린이집 주방 후드 필터를 분리 세척하고 안쪽 면을 닦은 기록입니다.",
    cta: "화성 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/hwaseong-hood-01.webp", "/images/regional/hwaseong-hood-05.webp"], "화성 어린이집 후드청소"),
  },
  {
    href: "/후드청소/서울특별시-영등포구/", province: "서울특별시", region: "영등포구", service: "후드청소",
    eyebrow: caseEyebrow, title: "서울 영등포구 후드청소",
    body: "어린이집 주방 후드 필터와 모서리, 배기구를 청소한 기록입니다.",
    cta: "영등포구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yeongdeungpo-hood-05.webp", "/images/regional/yeongdeungpo-hood-08.webp"], "서울 영등포구 어린이집 후드청소"),
  },
  {
    href: "/후드청소/인천광역시-연수구/", province: "인천광역시", region: "연수구", service: "후드청소",
    eyebrow: caseEyebrow, title: "인천 연수구 후드청소",
    body: "복지시설 주방 후드의 외부와 가장자리 홈, 안쪽 면을 청소한 기록입니다.",
    cta: "연수구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yeonsu-hood-02.webp", "/images/regional/yeonsu-hood-07.webp"], "인천 연수구 복지시설 후드청소"),
  },
  {
    href: "/학교청소/경기도-용인시/", province: "경기도", region: "용인시", service: "학교청소",
    eyebrow: caseEyebrow, title: "용인 학교청소",
    body: "초등학교 교실 공사 후 창틀과 수납장, 책상까지 청소한 기록입니다.",
    cta: "용인 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/yongin-school-05.webp", "/images/regional/yongin-school-13.webp"], "용인 초등학교 교실 학교청소"),
  },
  {
    href: "/침수청소/서울특별시-서초구/", province: "서울특별시", region: "서초구", service: "침수청소",
    eyebrow: caseEyebrow, title: "서울 서초구 침수청소",
    body: "지하 1층 주점에 물이 들어와 홀 바닥과 창고를 청소하고 건조한 기록입니다.",
    cta: "서초구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/jamwon-flood-03.webp", "/images/regional/jamwon-flood-08.webp"], "서울 서초구 지하 주점 침수청소"),
  },
  {
    href: "/침수청소/인천광역시-남동구/", province: "인천광역시", region: "남동구", service: "침수청소",
    eyebrow: caseEyebrow, title: "인천 남동구 침수청소",
    body: "남동공단 공장에 들어온 오수와 오물을 설비 주변까지 청소한 기록입니다.",
    cta: "남동구 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/namdong-flood-03.webp", "/images/regional/namdong-flood-08.webp"], "인천 남동공단 공장 침수청소"),
  },
  {
    href: "/침수청소/경기도-부천시/", province: "경기도", region: "부천시", service: "침수청소",
    eyebrow: caseEyebrow, title: "부천 침수청소",
    body: "지하 1층 작업장의 젖은 짐을 걷어내고 바닥과 단차를 청소한 기록입니다.",
    cta: "부천 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/wonmi-flood-01.webp", "/images/regional/wonmi-flood-11.webp"], "부천 원미구 지하 작업장 침수청소"),
  },
  {
    href: "/침수청소/경기도-안양시/", province: "경기도", region: "안양시", service: "침수청소",
    eyebrow: caseEyebrow, title: "안양 침수청소",
    body: "아파트 싱크대 역류로 흘러나온 오물을 하부장 안쪽까지 청소한 기록입니다.",
    cta: "안양 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/indeogwon-flood-04.webp", "/images/regional/indeogwon-flood-10.webp"], "안양 아파트 싱크대 역류 청소"),
  },
  {
    href: "/화재청소/경기도-성남시-분당구/", province: "경기도", region: "분당구", service: "화재청소",
    eyebrow: caseEyebrow, title: "분당 화재청소",
    body: "화재 후 사무실 바닥과 복도에 번진 그을음과 분진을 청소한 기록입니다.",
    cta: "분당 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/bundang-fire-01.webp", "/images/regional/bundang-fire-06.webp"], "성남 분당 사무실 건물 화재청소"),
  },
  {
    href: "/화재청소/경기도-화성시/", province: "경기도", region: "화성시", service: "화재청소",
    eyebrow: caseEyebrow, title: "화성 화재청소",
    body: "노래방 룸에 덮인 소화기 분말을 테이블과 소파, 바닥까지 청소한 기록입니다.",
    cta: "화성 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/dongtan-powder-01.webp", "/images/regional/dongtan-powder-04.webp"], "화성 동탄 노래방 소화기 분말 청소"),
  },
  {
    href: "/냄새-악취-제거/경기도-고양시/", province: "경기도", region: "고양시", service: "냄새악취제거",
    eyebrow: caseEyebrow, title: "고양 일산 냄새·악취 제거",
    body: "담뱃진으로 누렇게 변한 원룸 벽과 수납장, 창틀을 청소한 기록입니다.",
    cta: "고양 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/ilsan-nicotine-02.webp", "/images/regional/ilsan-nicotine-08.webp"], "고양 일산 원룸 니코틴 청소"),
  },
  {
    href: "/냄새-악취-제거/경기도-군포시/", province: "경기도", region: "군포시", service: "냄새악취제거",
    eyebrow: caseEyebrow, title: "군포 산본 냄새·악취 제거",
    body: "담뱃진이 앉은 환기 덕트와 천장 조명, 벽면을 청소한 기록입니다.",
    cta: "군포 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/sanbon-nicotine-01.webp", "/images/regional/sanbon-nicotine-08.webp"], "군포 산본 주택 니코틴 청소"),
  },
  {
    href: "/냄새-악취-제거/경기도-수원시/", province: "경기도", region: "수원시", service: "냄새악취제거",
    eyebrow: caseEyebrow, title: "수원 냄새·악취 제거",
    body: "담뱃진이 앉은 원룸 화장실과 창문을 청소한 기록입니다.",
    cta: "수원 사례와 견적 기준 보기",
    photos: pair(beforeAfter, ["/images/regional/suwon-nicotine-04.webp", "/images/regional/suwon-nicotine-06.webp"], "수원 원룸 니코틴 청소"),
  },
];

const unique = (values: string[]) => [...new Set(values)];
export const areaProvinces = unique(areaCases.map(c => c.province));
export const regionsOf = (province: string) => unique(areaCases.filter(c => c.province === province).map(c => c.region));
export const servicesOf = (province: string, region: string | null) =>
  unique(areaCases.filter(c => c.province === province && (!region || c.region === region)).map(c => c.service));
